# try1: no bug, RAM consumption too high, did not run successfully

In [1]:
import numpy as np # used for arrays

import gym # pull the environment

import time # to get the time

import math # needed for calculations

In [2]:
env = gym.make("CartPole-v1")
print(env.action_space.n)

2


In [3]:
LEARNING_RATE = 0.1

DISCOUNT = 0.95
EPISODES = 60000
total = 0
total_reward = 0
prior_reward = 0

Observation = [30, 30, 50, 50]
np_array_win_size = np.array([0.25, 0.25, 0.01, 0.1])

epsilon = 1

epsilon_decay_value = 0.99995

In [4]:
q_table = np.random.uniform(low=0, high=1, size=(Observation + [env.action_space.n]))
q_table.shape

(30, 30, 50, 50, 2)

In [15]:
def get_discrete_state(state):
    print(state)
    print(np_array_win_size)
    discrete_state = state/np_array_win_size+ np.array([15,10,1,10])
    return tuple(discrete_state.astype(int))

In [19]:
t0 = time.time() #set the initial time
discrete_state = get_discrete_state(env.reset()[0]) #get the discrete start for the restarted environment 
done = False
episode_reward = 0 #reward starts as 0 for each episode

if episode % 2000 == 0: 
    print("Episode: " + str(episode))

[-0.04085128  0.00973106 -0.04595046  0.0271315 ]
[0.25 0.25 0.01 0.1 ]
Episode: 0


In [20]:
if np.random.random() > epsilon:

    action = np.argmax(q_table[discrete_state]) #take cordinated action
else:

    action = np.random.randint(0, env.action_space.n) #do a random ation

In [22]:
print(action)

1


In [23]:
env.step(1)

(array([-0.03654704,  0.4012201 , -0.05100159, -0.58633953], dtype=float32),
 1.0,
 False,
 False,
 {})

In [24]:
new_state, reward, done, _, _ = env.step(action) #step action to get new states, reward, and the "done" status.

episode_reward += reward #add the reward

new_discrete_state = get_discrete_state(new_state)

[-0.02852264  0.5970179  -0.06272838 -0.8946423 ]
[0.25 0.25 0.01 0.1 ]


In [ ]:


while not done: 

    if np.random.random() > epsilon:

        action = np.argmax(q_table[discrete_state]) #take cordinated action
    else:

        action = np.random.randint(0, env.action_space.n) #do a random ation

    new_state, reward, done, _ = env.step(action) #step action to get new states, reward, and the "done" status.

    episode_reward += reward #add the reward

    new_discrete_state = get_discrete_state(new_state)

    if episode % 2000 == 0: #render
        env.render()

    if not done: #update q-table
        max_future_q = np.max(q_table[new_discrete_state])

        current_q = q_table[discrete_state + (action,)]

        new_q = (1 - LEARNING_RATE) * current_q + LEARNING_RATE * (reward + DISCOUNT * max_future_q)

        q_table[discrete_state + (action,)] = new_q

    discrete_state = new_discrete_state

if epsilon > 0.05: #epsilon modification
    if episode_reward > prior_reward and episode > 10000:
        epsilon = math.pow(epsilon_decay_value, episode - 10000)

        if episode % 500 == 0:
            print("Epsilon: " + str(epsilon))

t1 = time.time() #episode has finished
episode_total = t1 - t0 #episode total time
total = total + episode_total

total_reward += episode_reward #episode total reward
prior_reward = episode_reward

if episode % 1000 == 0: #every 1000 episodes print the average time and the average reward
    mean = total / 1000
    print("Time Average: " + str(mean))
    total = 0

    mean_reward = total_reward / 1000
    print("Mean Reward: " + str(mean_reward))
    total_reward = 0


In [18]:

for episode in range(EPISODES + 1): #go through the episodes
    t0 = time.time() #set the initial time
    discrete_state = get_discrete_state(env.reset()[0]) #get the discrete start for the restarted environment 
    done = False
    episode_reward = 0 #reward starts as 0 for each episode

    if episode % 2000 == 0: 
        print("Episode: " + str(episode))

    while not done: 

        if np.random.random() > epsilon:

            action = np.argmax(q_table[discrete_state]) #take cordinated action
        else:

            action = np.random.randint(0, env.action_space.n) #do a random ation

        new_state, reward, done, _, _ = env.step(action) #step action to get new states, reward, and the "done" status.

        episode_reward += reward #add the reward

        new_discrete_state = get_discrete_state(new_state)

        if episode % 2000 == 0: #render
            env.render()

        if not done: #update q-table
            max_future_q = np.max(q_table[new_discrete_state])

            current_q = q_table[discrete_state + (action,)]

            new_q = (1 - LEARNING_RATE) * current_q + LEARNING_RATE * (reward + DISCOUNT * max_future_q)

            q_table[discrete_state + (action,)] = new_q

        discrete_state = new_discrete_state

    if epsilon > 0.05: #epsilon modification
        if episode_reward > prior_reward and episode > 10000:
            epsilon = math.pow(epsilon_decay_value, episode - 10000)

            if episode % 500 == 0:
                print("Epsilon: " + str(epsilon))

    t1 = time.time() #episode has finished
    episode_total = t1 - t0 #episode total time
    total = total + episode_total

    total_reward += episode_reward #episode total reward
    prior_reward = episode_reward

    if episode % 1000 == 0: #every 1000 episodes print the average time and the average reward
        mean = total / 1000
        print("Time Average: " + str(mean))
        total = 0

        mean_reward = total_reward / 1000
        print("Mean Reward: " + str(mean_reward))
        total_reward = 0

env.close()

[-0.00423244  0.02434653 -0.04185093  0.02503614]
[0.25 0.25 0.01 0.1 ]
Episode: 0


/Users/yixinzhang/Desktop/cartpole/cptest/lib/python3.12/site-packages/gym/utils/passive_env_checker.py:233: DeprecationWarning: `np.bool8` is a deprecated alias for `np.bool_`.  (Deprecated NumPy 1.24)
  if not isinstance(terminated, (bool, np.bool8)):


ValueError: too many values to unpack (expected 4)

In [17]:
env.reset()

(array([ 0.04627293,  0.00452833, -0.04643157, -0.01921855], dtype=float32),
 {})